// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    marketplace
    (
        init => init
        upgrade => upgrade
        getListing => get_listing
        createListing => create_listing
        buyListing => buy_listing
        cancelListing => cancel_listing
        setRoyaltiesPercentage => set_royalties_percentage
        setRoyaltiesClaimAddress => set_royalties_claim_address
        createAuction => create_auction
        createOffer => create_offer
        acceptOffer => accept_offer
        cancelOffer => cancel_offer
        batchBuy => batch_buy
        pause => pause
        unpause => unpause
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
