// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    marketplace
    (
        init => init
        createListing => create_listing
        buyListing => buy_listing
        cancelListing => cancel_listing
        createAuction => create_auction
        placeBid => place_bid
        endAuction => end_auction
        getListing => get_listing
        getAuction => get_auction
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
